### ISSUE TITLE
Does this helm chart take care of installation order for clusterclass and cluster? 

### ISSUE THREAD

**Issue by meghasinghal186** [mboersma/cluster-api-charts#22]
While installation, or during any configuration update for ex adding new nodepool, clusterclass must be deployed/updated before cluster.
Does it take care of installation order?

**Comment by mboersma** [comment]
@meghasinghal186 I assume you're talking about the `azure-aks-aso` chart?

It does deploy the ClusterClass definitions to match the Cluster's objects, but I don't think there's an ordering enforced other than what Helm knows about core resources. @dtzar @nojnhuh please correct me if I'm wrong, or add your comments.

Is this causing an installation problem or some other error?

**Comment by dtzar** [comment]
The way I understand it - the helm chart just applies all the resources to the CAPZ management cluster and then it will just be in a reconcile loop until everything gets worked out.  No need to worry about order.

**Comment by meghasinghal186** [comment]
Yes, I was referring to `azure-aks-aso`.
I got it answered. Thanks.
